project:
  type: website
  output-dir: _manuscript
  render:
    - docs/*.qmd
    - notebooks/*.qmd
    # - reports/*.qmd
    - index.qmd
    - "!*unused/"
    - "!notebooks/c1*.qmd"

website: 
  sidebar: 
    style: "floating"
    search: true
    title: "Scaling Fiscal Shocks"
    contents:
      - index.qmd
      - auto: "*.qmd"


title-block-banner: true
lightbox: true
reference-location: margin

code-links: repo

execute:
  freeze: auto  # re-render only when source changes


citeproc: true
csl: https://www.zotero.org/styles/chicago-author-date-classic-no-url

bibliography: references.bib
