project:
  type: default
  output-dir: _manuscript
  render:
    - docs/*.qmd
    - notebooks/**/*.qmd
    - reports/*.qmd
    - index.qmd

title: "Scaling Narrative Fiscal Shock Identification with LLMs"
author: 
  - name: "Esteban Degetau"
    email: "estebandegetau@gmail.com"
  - name: "Agust√≠n Samano"
    email: "asamanopenaloza@worldbank.org"
date: today
date-format: long

code-links: repo

execute:
  freeze: auto  # re-render only when source changes

format:
  typst: default
  html: default

citeproc: true
csl: https://www.zotero.org/styles/chicago-author-date-classic-no-url

bibliography: references.bib
